/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * with Gradle
  */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
